name: haphzrd
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020106'
    - '#816327'
    - '#242e0c'
    - '#db9c4d'
    - '#98aaaa'
  brandStrength: 0.8125
  lightness: 0.0625
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
