name: haphzrd
favicon: null
layout_spectrum: 0.27047
typography_spectrum: 0.59428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040301'
    - '#93470d'
    - '#c17e38'
    - '#ffe0a7'
    - '#d5b386'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
